app:
  port: ':5100'
  time_format: '2006-01-02T15:04:05'

cache:
  address: '192.168.1.229'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  messages_key_format: 'messages.for.%s'