app:
  port: ':5100'
  cert_file: './cmd/api/certificate.pem'
  key_file: './cmd/api/key.pem'
  time_format: '2006-01-02T15:04:05'

cache:
  address: '192.168.0.105'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  messages_key_format: 'messages.for.%s'

health:
  port: ':8200'
  shutdown_endpoint: '/api/v1/superhero_offline_messages_health/shutdown'
  content_type: 'application/json'